image: python:latest

stages:
  - build-test

Python Package:
  stage: build-test
  script:
    - python -m pip install -r requirements.txt -r requirements-dev.txt
    - pylint --errors-only  src tests
    - pip install -e .
    - pytest --junitxml=report.xml
    - python -m build --wheel
  artifacts:
    when: always
    name: "SimStab Python API"
    paths: ["dist/*.whl"]
    reports:
      junit: report.xml
